### PR TITLE
CR003/adding_firmware_details

### PR DESCRIPTION
**Pull request by vschwaberow**
Adds links to source code and introduces firmware table

### CODE REVIEW

**Review by nox-x — APPROVED** [review]
a short branding-notice for the specific firmware version should be midterm added.
e.g. the version mentioned in README (01.01.117.01.EURO) is branded by Vodafone (and maybe also 01.02.068.11.EURO.SIP ?) while the version 01.02.025 seems to be the original Arris branded firmware

**Comment by vschwaberow** [comment]
One question: I saw only one version being published. But isn't Vodafone also obligated to publish their changes in source code format? Or am I getting it wrong. No License expert.

**Comment by nox-x** [comment]
Depending on the license model.
But afaik are most of the open-source components (listed in software.md) are GPL-licensed.
From manufacturers point of view only changed components with a GPL-license must be published.
If a manufacturer only use (and don't customized) some of these components they only must mention the used component.
I think the one published version of the source code (btw. containing only the OSS-components and not the closed source parts?!) you found (seems to be Arris-branded and not from Vodafone) was maybe published "by accident" or at least irregularly.

**Comment by vschwaberow** [comment]
Thanks for your view on this.

**Pull request merged**
